name = "Homestead"
author = "CozyStudios"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e6bed84e64b9533bd0ed7212036a09d4210366e4ff66954104ae700a2f20431"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
