name = "Homestead"
author = "CozyStudios"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1624f5b2deca6355d2620b5eb957c65cb3ae400fb5fc697469bc8d011d944e22"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
